### PR TITLE
Fixing targert binary for ARM processor and Linux distro

### PR DESCRIPTION
**Pull request by Marslanali**
Hi, 

Refers to issue #154 . The `package/CMakeList.txt` was not able to detect and select `armhf`, hence If we tried to build a package for a raspbian we will get i386 binary that you can not install on a raspberry pi using dpkg  `sudo dpkg -i ./radiotray-ng_0.2.7_raspbian_10_i386.deb`.

Therefore, we need to detect the processor architecture in `package/CmakeList.txt` before doing `cmake .. -DCMAKE_BUILD_TYPE=Release`. 

[Refer to this commit](https://github.com/Marslanali/radiotray-ng/commit/64e621dc6ba2a26244e27a10e137eb6e3a642458) and I've tested this on rasbain running on `${CMAKE_SYSTEM_PROCESSOR} :  armv7l` and now I am getting `radiotray-ng_0.2.7_raspbian_10_armhf.deb` which is working with `sudo dpkg -i ./radiotray-ng_0.2.7_raspbian_10_armhf.deb`.

Thanks 

Arslan Ali

### CODE REVIEW

**Comment by ebruck** [comment]
@Marslanali thanks for the PR!
Any chance you can also support arm64?

**Comment by Marslanali** [comment]
> @Marslanali thanks for the PR!
> Any chance you can also support for arm64?

Hi, 

@ebruck The development environment which I used to fix #154 was raspbian with `dpkg --print-architecture` shows up `armhf`. However, for `arm64` support, I need to set up a raspbian running on processor architecture `arm64` so that I can test whether  `package/CmakeList.txt` detect it or not.  

If you already have a raspbian setup with `dpkg --print-architecture` : arm64. Can you share it via SSH?. 

Also to test `arm64` we need to make sure `${CMAKE_SYSTEM_PROCESSOR}`  shows: `armv8` because to the best of my knowledge, the ARM architecture offering 64-bit support is `armv8`.

Let me know your thoughts on this and another workaround is to have a development environment local at my end.

**Comment by ebruck** [comment]
@Marslanali sorry, but I don't have any Raspberry PI 4s for testing.

**Comment by Marslanali** [comment]
@ebruck Let me have a look into it, and I will commit the necessary changes once I have access to correct development environment for testing i.e Raspberry PI 4s.

**Comment by MooglyRidge** [comment]
Not sure if you only need an arm64 device to test a build on or if you need one to actually write changes to the source, but since I was looking for an arm64 version of radiotray-ng and found this, I wouldn't mind trying it out if it helps out.
I run Ubuntu 18.04 on arm64 (Nintendo Switch), I'd be willing to install and test it for you here.

**Comment by Marslanali** [comment]
@MooglyRidge Thanks & Sounds good. 

> I run Ubuntu 18.04 on arm64 (Nintendo Switch), I'd be willing to build and test it for you here.

Yes, that would be great. I will have a look into the CMakeList.txt to do necessary amendments, will commit changes to current #155 PR, and then you can build at your end to see if it detect and generate a binary for arm64. 

Thanks

**Comment by Marslanali** [comment]
Hi @MooglyRidge,

Sorry for the delay in revising current #155. To add support for arm64, [Rerfers to this update commit] (https://github.com/Marslanali/radiotray-ng/commit/cf4eef067233281beb5b5d571ec38410d8b84406). 

Would you mind to test it on Ubuntu 18.04 running on arm64? Since I don't have access to the arm64 device running Linux so I am unable to verify whether [these changes](https://github.com/Marslanali/radiotray-ng/commit/cf4eef067233281beb5b5d571ec38410d8b84406) will correctly detect arm64 while generating binary for the arm64 target platform.

**Comment by MooglyRidge** [comment]
Hey @Marslanali :)
No worries, things are busy so I understand!

I just gave the build a shot, and while it doesn't give any errors, it generates a binary for amd64. While I'm unsure if it makes a difference, I also tried with aarch64 in CMakeLists.txt instead of arm64, but it yielded the same result.

Tried building both release and debug.

**Comment by Marslanali** [comment]
Hi @MooglyRidge,

Thanks for testing, would you share the terminal output of the following cmd:

$ sudo dpkg --print-architecture


Also, can you share with me the terminal log by running the following `CMakeLists.txt` with a simple  `C++ hello world program`? This will give me a better insight into your target platform. 

```bash
cmake_minimum_required(VERSION 3.17)
project(test)

set(CMAKE_CXX_STANDARD 17)

message(STATUS "CMake version   : " ${CMAKE_SYSTEM_VERSION})
message(STATUS "Compiler        : " ${CMAKE_CXX_COMPILER})
message(STATUS "Operating System: " ${CMAKE_SYSTEM})
message(STATUS "CMAKE_SYSTEM_PROCESSOR   : " ${CMAKE_SYSTEM_PROCESSOR})
message(STATUS "CPACK_SYSTEM_NAME         : " ${CPACK_SYSTEM_NAME})

add_executable(test main.cpp)
``` 

You can test and build above CmakeLists.txt with `hello_world main.cpp` using following cmds:


```bash
$ mkdir test   &&  cd test 
$ vim main.cpp   #  copy hello world cpp
$ vim CMakeLists.txt   # copy CmakeList file here
$ cmake .. 
$ make 
$ ./test
```

Thanks!

**Comment by MooglyRidge** [comment]
@Marslanali

Sure thing! Sorry for the delay, things were a little busy. Hope the holidays have treated you nice so far.

`dpkg --print-architecture`
This prints arm64 as expected.

As for cmake, I'm running version 3.10 and couldn't find a way to get 3.17, at least in any obvious way, so I had to replace `cmake_minimum_required(VERSION 3.17)` with VERSION 3.10

It then prints as follows:
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake version   : 4.9.140+
-- Compiler        : /usr/bin/c++
-- Operating System: Linux-4.9.140+
-- CMAKE_SYSTEM_PROCESSOR   : aarch64
-- CPACK_SYSTEM_NAME         : 

Let me know if I need to do something differently, and I'll do my best.

**Comment by Marslanali** [comment]
Hi @MooglyRidge, 

Thanks for testing it out, and I will be revising the previous commit and you can test it afterwards. 

The `CMAKE_SYSTEM_PROCESSOR` flag outputs `aarch64` for your target platform so it's worth trying the following changes in `package/CMakeLists.txt`.

For instance, 

```bash 
- elseif(CMAKE_SYSTEM_PROCESSOR  MATCHES "arm64")
+ elseif(CMAKE_SYSTEM_PROCESSOR  MATCHES "aarch64")
```

Apologize for the delays in my response. However, I will truly back to you soon with changes. 

Thanks!

**Comment by MooglyRidge** [comment]
I actually tried with aarch64 the first time, but it still made an amd64 binary 🤔

Thank you for your time! I appreciate that you want to help getting this set up for this architecture.

**Comment by ebruck** [comment]
@Marslanali can you please post the contents of rtng_user_agent.hpp?
Just want to verify that it's being created correctly. Thanks for your work so far!

**Comment by Marslanali** [comment]
Hi @MooglyRidge,

oh right :-(  I thought the `aarch64` flag in `CMAKE_SYSTEM_PROCESSOR` would do the job. Nonetheless, we can check some other workarounds and I believe with few more changes we can correctly detect architecture for the target platform.

**Comment by Marslanali** [comment]
> rtng_user_agent.hpp
 @ebruck

previously I've not checked `rtng_user_agent.hpp` but I share the content of `rtng_user_agent.hpp` after I generate a binary file on my current x86 platform. But the binary file will be for x86 architecture, not the arm based architecture.

**Comment by Marslanali** [comment]
Hi @MooglyRidge, @ebruck 

Would you mind sharing your thoughts on any other workaround we can opt to add the support for the arm64 architecture for this project? I now have raspberry pie zero and I can test there and will see if that would address the arm64 architecture support issue. 

Have a great weekend!

Arslan

**Comment by Marslanali** [comment]
#155 PR closed.

**Comment by 2play** [comment]
arm64 & arm commit as per https://github.com/ebruck/radiotray-ng/pull/232
i have tested and created an arm64 deb on RPi5. Both on master and 0.2.10 branch,
Ubuntu Noble
screenshot

**Pull request closed without merging**
